#pragma once

#ifndef SETTINGS_LIB_VERSION_HPP
#define SETTINGS_LIB_VERSION_HPP

//
// Settings Library Build Type
//

// Settings Libray build type:
// 1 - Alpha
// 2 - Beta
// 3 - Release Candidate
// 4 - Release
#define SETTINGS_LIB_COMPILE_BUILD_TYPE 1

#if SETTINGS_LIB_COMPILE_BUILD_TYPE == 1
	#define SETTINGS_LIB_BUILD_TYPE_ALPHA					// Settings Library to compile with alpha features
#elif SETTINGS_LIB_COMPILE_BUILD_TYPE == 2
	#define SETTINGS_LIB_BUILD_TYPE_BETA					// Settings Library to compile with beta features
#elif SETTINGS_LIB_COMPILE_BUILD_TYPE == 3
	#define SETTINGS_LIB_BUILD_TYPE_RELEASE_CANDIDATE		// Settings Library to compile with release candidate features
#elif SETTINGS_LIB_COMPILE_BUILD_TYPE == 4
	#define SETTINGS_LIB_BUILD_TYPE_RELEASE					// Settings Library to compile with release features
#else
	#error "No SettingsLib build type is defined!"
#endif // !SETTINGS_LIB_BUILD_TYPE

//
// Settings Library Build:
//

#ifdef SETTINGS_LIB_BUILD_TYPE_ALPHA
	#define SETTINGS_LIBRARY_MAJOR_VERSION 3
	#define SETTINGS_LIBRARY_MINOR_VERSION 0
	#define SETTINGS_LIBRARY_PATCH_VERSION 0
	#define SETTINGS_LIBRARY_BUILD_NUMBER 63
	#define SETTINGS_LIBRARY_BUILD_TYPE "alpha"
	#define SETTINGS_LIBRARY_REVISION_NUMBER 30
#endif // !SETTINGS_LIB_BUILD_TYPE_ALPHA

#ifdef SETTINGS_LIB_BUILD_TYPE_BETA
	#define SETTINGS_LIBRARY_MAJOR_VERSION 3
	#define SETTINGS_LIBRARY_MINOR_VERSION 0
	#define SETTINGS_LIBRARY_PATCH_VERSION 0
	#define SETTINGS_LIBRARY_BUILD_NUMBER 63
	#define SETTINGS_LIBRARY_BUILD_TYPE "beta"
	#define SETTINGS_LIBRARY_REVISION_NUMBER 30
#endif // !SETTINGS_LIB_BUILD_TYPE_BETA

#ifdef SETTINGS_LIB_BUILD_TYPE_RELEASE_CANDIDATE
	#define SETTINGS_LIBRARY_MAJOR_VERSION 3
	#define SETTINGS_LIBRARY_MINOR_VERSION 0
	#define SETTINGS_LIBRARY_PATCH_VERSION 0
	#define SETTINGS_LIBRARY_BUILD_NUMBER 63
	#define SETTINGS_LIBRARY_BUILD_TYPE "release candidate"
	#define SETTINGS_LIBRARY_REVISION_NUMBER 30
#endif // !SETTINGS_LIB_BUILD_TYPE_RELEASE_CANDIDATE

#ifdef SETTINGS_LIB_BUILD_TYPE_RELEASE
	#define SETTINGS_LIBRARY_MAJOR_VERSION 3
	#define SETTINGS_LIBRARY_MINOR_VERSION 0
	#define SETTINGS_LIBRARY_PATCH_VERSION 0
	#define SETTINGS_LIBRARY_BUILD_NUMBER 63
	#define SETTINGS_LIBRARY_BUILD_TYPE "release"
	#define SETTINGS_LIBRARY_REVISION_NUMBER 30
#endif // !SETTINGS_LIB_BUILD_TYPE_RELEASE

#endif // !SETTINGS_LIB_VERSION_HPP