#pragma once

#ifndef LOGGER_LIB_VERSION_HPP
#define LOGGER_LIB_VERSION_HPP

#define LOGGER_LIB_MAJOR_VERSION 3
#define LOGGER_LIB_MINOR_VERSION 3
#define LOGGER_LIB_PATCH_VERSION 0
#define LOGGER_LIB_BUILD_NUMBER 81
#define LOGGER_LIB_BUILD_TYPE "alpha"
#define LOGGER_LIB_REVISION_NUMBER 9

#endif // !LOGGER_LIB_VERSION_HPP