#pragma once

#ifndef LOGGER_LIB_VERSION_HPP
#define LOGGER_LIB_VERSION_HPP

#define LOGGER_LIB_MAJOR_VERSION 3
#define LOGGER_LIB_MINOR_VERSION 1
#define LOGGER_LIB_PATCH_VERSION 1
#define LOGGER_LIB_BUILD_NUMBER 42
#define LOGGER_LIB_BUILD_TYPE "release"
#define LOGGER_LIB_REVISION_NUMBER 0

#endif // !LOGGER_LIB_VERSION_HPP