#pragma once

#ifndef LOGGER_LIB_VERSION_HPP
#define LOGGER_LIB_VERSION_HPP

#define LOGGER_LIB_MAJOR_VERSION 3
#define LOGGER_LIB_MINOR_VERSION 3
#define LOGGER_LIB_PATCH_VERSION 0
#define LOGGER_LIB_BUILD_NUMBER 73
#define LOGGER_LIB_BUILD_TYPE "alpha"
#define LOGGER_LIB_REVISION_NUMBER 5

#endif // !LOGGER_LIB_VERSION_HPP