#pragma once

#ifndef VERSION_LIB_VERSION_INFO_HPP
#define VERSION_LIB_VERSION_INFO_HPP

//
// Version Library Build Type
//

// Version Libray build type:
// 1 - Alpha
// 2 - Beta
// 3 - Release Candidate
// 4 - Release
#define VERSION_LIB_BUILD_TYPE 1

#if VERSION_LIB_BUILD_TYPE == 1
	#define VERSION_LIB_BUILD_TYPE_ALPHA				// Version Library to compile with alpha features
#elif VERSION_LIB_BUILD_TYPE == 2
	#define VERSION_LIB_BUILD_TYPE_BETA					// Version Library to compile with beta features
#elif VERSION_LIB_BUILD_TYPE == 3
	#define VERSION_LIB_BUILD_TYPE_RELEASE_CANDIDATE	// Version Library to compile with release candidate features
#elif VERSION_LIB_BUILD_TYPE == 4
	#define VERSION_LIB_BUILD_TYPE_RELEASE				// Version Library to compile with release features
#else
	#error "No VersionLib build type is defined!"
#endif // !VERSION_LIB_BUILD_TYPE

//
// Version Library Build:
//

#ifdef VERSION_LIB_BUILD_TYPE_ALPHA
	#define VERSION_LIB_VERSION_INFO_MAJOR_VERSION 0
	#define VERSION_LIB_VERSION_INFO_MINOR_VERSION 9
	#define VERSION_LIB_VERSION_INFO_PATCH_VERSION 0
	#define VERSION_LIB_VERSION_INFO_BUILD_NUMBER 90
	#define VERSION_LIB_VERSION_INFO_BUILD_TYPE "alpha"
	#define VERSION_LIB_VERSION_INFO_BUILD_TYPE_NUMBER 3
#endif // !VERSION_LIB_BUILD_TYPE_ALPHA

#ifdef VERSION_LIB_BUILD_TYPE_BETA
	#define VERSION_LIB_VERSION_INFO_MAJOR_VERSION 0
	#define VERSION_LIB_VERSION_INFO_MINOR_VERSION 8
	#define VERSION_LIB_VERSION_INFO_PATCH_VERSION 7
	#define VERSION_LIB_VERSION_INFO_BUILD_NUMBER 70
	#define VERSION_LIB_VERSION_INFO_BUILD_TYPE "beta"
	#define VERSION_LIB_VERSION_INFO_BUILD_TYPE_NUMBER 1
#endif // !VERSION_LIB_BUILD_TYPE_BETA

#ifdef VERSION_LIB_BUILD_TYPE_RELEASE_CANDIDATE
	#define VERSION_LIB_VERSION_INFO_MAJOR_VERSION 0
	#define VERSION_LIB_VERSION_INFO_MINOR_VERSION 8
	#define VERSION_LIB_VERSION_INFO_PATCH_VERSION 6
	#define VERSION_LIB_VERSION_INFO_BUILD_NUMBER 53
	#define VERSION_LIB_VERSION_INFO_BUILD_TYPE "release candidate"
	#define VERSION_LIB_VERSION_INFO_BUILD_TYPE_NUMBER 0
#endif // !VERSION_LIB_BUILD_TYPE_RELEASE_CANDIDATE

#ifdef VERSION_LIB_BUILD_TYPE_RELEASE
	#define VERSION_LIB_VERSION_INFO_MAJOR_VERSION 0
	#define VERSION_LIB_VERSION_INFO_MINOR_VERSION 8
	#define VERSION_LIB_VERSION_INFO_PATCH_VERSION 6
	#define VERSION_LIB_VERSION_INFO_BUILD_NUMBER 53
	#define VERSION_LIB_VERSION_INFO_BUILD_TYPE "release"
	#define VERSION_LIB_VERSION_INFO_BUILD_TYPE_NUMBER 0
#endif // !VERSION_LIB_BUILD_TYPE_RELEASE

#endif // !VERSION_LIB_VERSION_INFO_HPP