#pragma once

#ifndef VERSION_LIB_VERSION_INFO_HPP
#define VERSION_LIB_VERSION_INFO_HPP

#define VERSION_LIB_VERSION_INFO_MAJOR_VERSION 0
#define VERSION_LIB_VERSION_INFO_MINOR_VERSION 8
#define VERSION_LIB_VERSION_INFO_PATCH_VERSION 2
#define VERSION_LIB_VERSION_INFO_BUILD 25
#define VERSION_LIB_VERSION_INFO_BUILD_TYPE "beta"
#define VERSION_LIB_VERSION_INFO_BUILD_TYPE_NUMBER 1

#endif // !VERSION_LIB_VERSION_INFO_HPP