#pragma once

#ifndef VERSION_LIB_VERSION_INFO_HPP
#define VERSION_LIB_VERSION_INFO_HPP

#define VERSION_LIB_VERSION_INFO_MAJOR_VERSION 0
#define VERSION_LIB_VERSION_INFO_MINOR_VERSION 8
#define VERSION_LIB_VERSION_INFO_PATCH_VERSION 3
#define VERSION_LIB_VERSION_INFO_BUILD_NUMBER 31
#define VERSION_LIB_VERSION_INFO_BUILD_TYPE "beta"
#define VERSION_LIB_VERSION_INFO_BUILD_TYPE_NUMBER 2

#endif // !VERSION_LIB_VERSION_INFO_HPP